<a href="https://colab.research.google.com/github/jim-min/gdsc-ai-study/blob/main/boostcamp/boostcamp_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Torch에서는 텐서를 사용해서 다차원 배열을 다룸

import torch
import numpy as np

n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim :", n_array.ndim, "shape :", n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 shape : (2, 5)


In [4]:
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape :", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape : torch.Size([2, 5])


In [5]:
data = [[3,5], [10, 5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

In [7]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

In [7]:
x_data.flatten()

torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [14]:
x_data.device

device(type='cpu')

In [8]:
if torch.cuda.is_available():
  x_data_cuda = x_data.to('cuda')

x_data_cuda.device

device(type='cuda', index=0)

In [20]:
tensor_ex = torch.rand(size=(2,3,2))
tensor_ex

tensor_ex.view(-1, 6)  #tensor은 view를 쓰는 게 좋을 때도 있음 출력 형태만 바꿔줄 때
tensor_ex.reshape(-1, 6)

tensor([[0.4902, 0.4350, 0.6155, 0.8263, 0.5940, 0.5135],
        [0.3899, 0.1340, 0.3893, 0.8003, 0.3848, 0.9355]])

In [49]:
tensor_ex = torch.rand(size=(2,3,1))

tensor_ex.squeeze()

tensor_ex.unsqueeze(0)
tensor_ex.shape

torch.Size([2, 3, 1])

In [50]:
# 행렬곱셈할 때는 mm을 사용 (matrix multiplication)

n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)

t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [53]:
a = torch.rand(5,2,3)
b = torch.rand(3)

print(a)

# a.mm(b) 이렇게 쓰면 broadcast 안 됨
a.matmul(b)

tensor([[[0.8496, 0.5450, 0.7718],
         [0.3682, 0.9221, 0.2186]],

        [[0.9588, 0.3553, 0.9970],
         [0.4736, 0.5388, 0.8425]],

        [[0.9539, 0.6897, 0.8909],
         [0.1021, 0.1809, 0.7176]],

        [[0.5221, 0.4929, 0.0396],
         [0.7423, 0.0949, 0.7272]],

        [[0.6259, 0.6850, 0.5652],
         [0.0901, 0.1871, 0.8611]]])


tensor([[1.0229, 1.0916],
        [0.9094, 0.7954],
        [1.2222, 0.2364],
        [0.7751, 0.5333],
        [1.0218, 0.2361]])

In [54]:
import torch.nn.functional as Func

tensorF = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = Func.softmax(tensorF, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [55]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 2*y + 5

z.backward()  # 미분
w.grad

tensor(8.)